import {test,expect,type Page} from '@playwright/test';
import ExcelJS from 'exceljs';
import fs from 'node:fs/promises';
import {abrirProjeto} from '../src/projeto/arquivo';
import {criarModeloExcel,lerPlanilha} from '../src/projeto/planilha';
import {novoProjetoCampo} from '../src/relatorios/campo/modelo';
const foto='src/identidade/simbolo.png';
async function abrir(page:Page,nome:string){await page.goto('/');await page.getByRole('button',{name:new RegExp('MODELO DISPONÍVEL.*'+nome)}).click();}
const pronto=(page:Page)=>expect(page.getByRole('button',{name:/Exportar PDF/})).toBeEnabled();
const semEstouro=(page:Page)=>page.frameLocator('iframe').locator('.record-page main').evaluateAll(ns=>ns.every(n=>n.scrollHeight<=n.clientHeight+1));
async function salvarEReabrir(page:Page,nome:string){
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:/Salvar projeto/}).click();await (await downloading).saveAs(`test-results/${nome}.bcrel`);
 const restored=await abrirProjeto(new Uint8Array(await fs.readFile(`test-results/${nome}.bcrel`)).buffer);
 await page.getByRole('button',{name:/Todos os relatórios/}).click();await page.locator('input[accept=".bcrel"]').setInputFiles(`test-results/${nome}.bcrel`);
 return restored;
}
test('visita técnica: texto longo continua nas páginas sem perder conteúdo',async({page})=>{
 await abrir(page,'Relatório de Visita Técnica');
 await page.getByLabel('Cliente',{exact:true}).fill('Hospital Central');
 await page.getByLabel('Objetivo da visita',{exact:true}).fill('Avaliar o sistema de ar-condicionado central.');
 await page.getByRole('button',{name:/02.*Constatações/}).click();
 await page.getByRole('button',{name:/Adicionar constatação/}).click();
 await page.getByLabel('Constatação',{exact:true}).fill('Filtros saturados');
 await page.getByLabel('Local / sistema',{exact:true}).fill('Casa de máquinas · AHU-01');
 const longo='Filtros com acúmulo de sujidade acima do aceitável.\n'.repeat(40)+'FIM';
 await page.getByLabel('Descrição da constatação',{exact:true}).fill(longo);
 await page.getByLabel('Recomendação',{exact:true}).fill('Substituir os filtros G4 e F7.');
 await page.locator('.photo-field input').setInputFiles(foto);
 await page.getByRole('button',{name:/03.*Conclusão/}).click();
 await page.getByLabel('Conclusão e recomendações',{exact:true}).fill('Sistema operando com restrições.');
 await pronto(page);
 const frame=page.frameLocator('iframe');
 const textos=await frame.locator('.campo-visita .activity-text').allTextContents();
 expect(textos.join('')).toBe(longo+'Substituir os filtros G4 e F7.');
 expect(await frame.locator('.campo-visita').count()).toBeGreaterThan(1);
 expect(await frame.locator('.campo-visita.continuation .page-media').count()).toBe(0);
 await expect(frame.locator('.campo-texto h2')).toHaveText(['Objetivo da visita','Conclusão e recomendações']);
 expect(await semEstouro(page)).toBe(true);
 const restored=await salvarEReabrir(page,'visita');
 expect(restored.modelo).toBe('visita');if(restored.modelo!=='visita')throw Error();expect(restored.itens[0].foto).toMatch(/^data:image\/png/);expect(restored.conclusao).toBe('Sistema operando com restrições.');
 await expect(page.getByLabel('Cliente',{exact:true})).toHaveValue('Hospital Central');
});
test('fotográfico: várias fotos de uma vez e grade por página',async({page})=>{
 await abrir(page,'Relatório Fotográfico');
 await page.getByLabel('Cliente',{exact:true}).fill('Shopping Norte');
 await page.getByRole('button',{name:/02.*Fotos/}).click();
 await page.locator('.multi-photo input').setInputFiles(Array(5).fill(foto));
 await expect(page.getByText('5 registro(s)')).toBeVisible();
 await page.getByLabel('Legenda da foto',{exact:true}).fill('Fachada principal');
 await page.getByRole('button',{name:/Mover para baixo/}).click();
 await pronto(page);
 const frame=page.frameLocator('iframe');
 await expect(frame.locator('.photo-page')).toHaveCount(2);
 await expect(frame.locator('.photo-page figcaption').nth(1)).toContainText('Fachada principal');
 await page.getByRole('button',{name:/01.*Capa e dados/}).click();
 await page.getByLabel('Fotos por página',{exact:true}).selectOption('6');
 await pronto(page);
 await expect(frame.locator('.photo-page')).toHaveCount(1);
 expect(await frame.locator('.photo-page main').evaluateAll(ns=>ns.every(n=>n.scrollHeight<=n.clientHeight+1))).toBe(true);
 await expect(frame.locator('.campo-texto')).toHaveCount(0);
 await expect(frame.locator('.title-page h1')).toHaveText('Shopping Norte');
 await page.getByLabel('Obra (opcional)',{exact:true}).fill('Reforma bloco B');
 await page.getByRole('button',{name:/03.*Conclusão/}).click();
 await page.getByLabel('Conclusão',{exact:true}).fill('Serviços concluídos conforme registros.');
 await pronto(page);
 await expect(frame.locator('.campo-texto h2')).toHaveText('Conclusão');
 await expect(frame.locator('.page').nth(-2)).toHaveClass(/campo-texto/);
 await expect(frame.locator('.photo-page footer span').first()).toHaveText('Shopping Norte · Reforma bloco B');
 const imgs=await frame.locator('.photo-page figure>img').evaluateAll(ns=>ns.map(n=>n.getBoundingClientRect().height));
 expect(imgs.every(h=>h>100)).toBe(true);
});
test('limpeza de dutos: marcação na planta, antes e depois e arquivo portátil',async({page})=>{
 await abrir(page,'Relatório de Limpeza de Dutos');
 await page.getByLabel('Cliente',{exact:true}).fill('Edifício Aurora');
 await page.getByRole('button',{name:/02.*Pontos de limpeza/}).click();
 for(const nome of ['Insuflamento 1º andar','Retorno 2º andar']){await page.getByRole('button',{name:/Adicionar ponto de limpeza/}).click();await page.getByLabel('Identificação do ponto',{exact:true}).fill(nome);}
 await page.locator('.photo-field input').first().setInputFiles(foto);
 await page.getByRole('button',{name:/03.*Mapas de limpeza/}).click();
 await page.locator('label.upload input').setInputFiles(foto);
 await page.getByLabel('Nome da planta',{exact:true}).fill('Planta 1º pavimento');
 await page.getByRole('button',{name:'Abrir planta para marcação'}).click();
 const modal=page.getByRole('dialog',{name:'Planta 1º pavimento'});await expect(modal).toBeVisible();
 await modal.getByLabel('Ponto a marcar').selectOption({label:'02 · Retorno 2º andar'});
 await modal.getByLabel('Planta para marcação').click({position:{x:60,y:40}});
 await modal.getByLabel('Ponto a marcar').selectOption({label:'01 · Insuflamento 1º andar'});
 await modal.getByRole('button',{name:'Cor clara'}).click();
 await modal.getByLabel('Planta para marcação').click({position:{x:150,y:80}});
 await modal.getByRole('button',{name:/Contornar duto/}).click();await modal.getByRole('button',{name:'Cor média'}).click();
 const box=(await modal.getByLabel('Planta para marcação').boundingBox())!;
 await page.mouse.move(box.x+20,box.y+60);await page.mouse.down();
 for(const [dx,dy] of [[90,60],[90,100],[20,100],[20,62]])await page.mouse.move(box.x+dx,box.y+dy,{steps:6});
 await page.mouse.up();
 await expect(modal.locator('.map-editor .pin')).toHaveCount(3);await expect(modal.locator('.map-editor .contornos path')).toHaveCount(1);
 await modal.getByRole('button',{name:'Concluir'}).click();await expect(modal).toBeHidden();
 await expect(page.locator('.map-thumb .pin')).toHaveCount(3);
 await pronto(page);
 const frame=page.frameLocator('iframe');
 await expect(frame.locator('.map-page .pin:not(.static)')).toHaveText(['02','01','01']);
 await expect(frame.locator('.map-page .contornos path.cor-media')).toHaveCount(1);
 await expect(frame.locator('.map-page .pin:not(.static)')).toHaveClass([/cor-escura/,/cor-clara/,/cor-media/]);
 await expect(frame.locator('.campo-dutos .mini-map')).toHaveCount(2);
 await expect(frame.locator('.campo-dutos').first().locator('.mini-map .pin')).toHaveText(['01','01']);
 expect(await semEstouro(page)).toBe(true);
 await expect(frame.locator('.map-legend li')).toHaveCount(2);
 await expect(frame.locator('.campo-dutos')).toHaveCount(2);
 await expect(frame.locator('.campo-dutos').first().locator('figcaption')).toHaveText(['Antes da limpeza','Depois da limpeza']);
 const print=await page.context().newPage();await print.setContent(await frame.locator('html').evaluate(n=>n.outerHTML));await print.locator('.map-page').screenshot({path:'test-results/dutos-mapa.png'});await print.locator('.campo-dutos').first().screenshot({path:'test-results/dutos-limpeza.png'});await page.getByRole('button',{name:'Abrir planta para marcação'}).click();await page.screenshot({path:'test-results/dutos-modal.png'});await page.getByRole('dialog').getByRole('button',{name:'Concluir'}).click();await print.close();
 const restored=await salvarEReabrir(page,'dutos');
 if(restored.modelo!=='dutos')throw Error();expect(restored.mapas[0].marcadores.length).toBe(3);expect(restored.mapas[0].marcadores[2].contorno!.length).toBeGreaterThan(5);expect(restored.mapas[0].marcadores.map(m=>m.cor)).toEqual(['escura','clara','media']);expect(restored.mapas[0].imagem).toMatch(/^data:image\/png/);
 await page.getByRole('button',{name:/02.*Pontos de limpeza/}).click();
 await page.getByRole('button',{name:'Remover registro'}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();
 await page.getByRole('button',{name:/03.*Mapas de limpeza/}).click();
 await expect(page.locator('.map-thumb .pin')).toHaveCount(1);await expect(page.locator('.map-thumb .contornos path')).toHaveCount(0);
});
test('apontamentos: uma página por apontamento, sem tabelas',async({page})=>{
 await abrir(page,'Relatório de Apontamentos');
 await page.getByRole('button',{name:/02.*Apontamentos/}).click();
 await page.getByRole('button',{name:/Adicionar apontamento/}).click();
 await page.getByLabel('Apontamento',{exact:true}).fill('Isolamento danificado');
 await page.getByLabel('Descrição do apontamento',{exact:true}).fill('Trecho de 2 m sem isolamento térmico.');
 await page.locator('.photo-field input').setInputFiles(foto);
 await pronto(page);
 const frame=page.frameLocator('iframe');
 await expect(frame.locator('.page')).toHaveCount(4);
 await expect(frame.locator('.campo-apontamento h2')).toHaveText('Isolamento danificado');
 expect(await frame.locator('table').count()).toBe(0);
 expect(await semEstouro(page)).toBe(true);
});
test('Excel: modelo e importação dos relatórios de campo',async()=>{
 const wb=new ExcelJS.Workbook();await wb.xlsx.load(await criarModeloExcel('dutos') as unknown as ExcelJS.Buffer);
 const ws=wb.getWorksheet('Pontos de limpeza')!;
 const col=(label:string)=>{let c=0;ws.getRow(1).eachCell((cell,n)=>{if(cell.text===label)c=n;});return c;};
 ws.getCell(2,col('Identificação do ponto')).value='Trecho A';ws.getCell(3,col('Identificação do ponto')).value='Trecho B';
 const image=wb.addImage({buffer:await fs.readFile(foto),extension:'png'});ws.addImage(image,{tl:{col:col('Foto depois da limpeza')-1,row:1},ext:{width:80,height:40}});
 wb.getWorksheet('Informações gerais')!.getCell(2,1).value='Obra importada';
 const atual=novoProjetoCampo('dutos');atual.conclusao='preservada';
 const result=await lerPlanilha(new Uint8Array(await wb.xlsx.writeBuffer()).buffer,atual);
 expect(result.erros).toEqual([]);expect(result.quantidade).toBe(2);expect(result.fotos).toBe(1);
 if(result.projeto.modelo!=='dutos')throw Error();
 expect(result.projeto.gerais.cliente).toBe('Obra importada');expect(result.projeto.itens[0].fotoDepois).toMatch(/^data:image\/png/);expect(result.projeto.conclusao).toBe('preservada');
 await expect(lerPlanilha(new Uint8Array(await wb.xlsx.writeBuffer()).buffer,novoProjetoCampo('visita'))).rejects.toThrow('Visita Técnica');
});
