import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import {abrirProjeto} from '../src/projeto/arquivo';
test('avanço de obras: campos, imagens, arquivo portátil e PDF horizontal',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/MODELO DISPONÍVEL.*Relatório de Avanço/}).click();
 await page.getByLabel('Nome da obra',{exact:true}).fill('Obra Damata');
 await page.getByLabel('Tipo de relatório',{exact:true}).fill('AVANÇO DE OBRA — DUTOS');
 await page.getByRole('button',{name:/02.*Registros fotográficos/}).click();
 await page.getByRole('button',{name:/Adicionar registro fotográfico/}).click();
 await page.getByLabel('Serviço realizado',{exact:true}).fill('Instalações de Rede de Dutos');
 await page.getByLabel('Pavimento',{exact:true}).fill('3º Subsolo');
 await page.locator('.photo-field input').setInputFiles('src/identidade/simbolo.png');
 await page.getByLabel('Legenda do registro fotográfico',{exact:true}).fill('Planta do 3º subsolo');
 await page.getByLabel('Resumo/Descrição das atividades realizadas',{exact:true}).fill('Instalação de 25 metros de dutos de exaustão.');
 await page.getByRole('button',{name:/03.*Registros descritivos/}).click();
 await page.getByRole('button',{name:/Adicionar registro descritivo/}).click();
 await page.getByLabel('Serviço realizado',{exact:true}).fill('Medições de rede de dutos');
 await page.getByLabel('Tipo de descrição',{exact:true}).fill('Avanço financeiro');
 const long='Descrição detalhada das atividades realizadas.\n'.repeat(100)+'FIM';
 await page.getByLabel('Resumo/Descrição das atividades realizadas',{exact:true}).fill(long);
 await expect(page.getByRole('button',{name:/Exportar PDF/})).toBeEnabled();
 const frame=page.frameLocator('iframe');
 expect((await frame.locator('.descritivo .activity-text').allTextContents()).join('')).toBe(long);
 expect(await frame.locator('.record-page main').evaluateAll(ns=>ns.some(n=>n.scrollHeight>n.clientHeight+1))).toBe(false);
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:/Salvar projeto/}).click();const download=await downloading;await download.saveAs('test-results/obras.bcrel');
 const bytes=await fs.readFile('test-results/obras.bcrel');const restored=await abrirProjeto(new Uint8Array(bytes).buffer);expect(restored.modelo).toBe('obras');expect(restored.itens.length).toBe(2);
 await page.getByRole('button',{name:/Todos os relatórios/}).click();await page.locator('input[accept=".bcrel"]').setInputFiles('test-results/obras.bcrel');
 await expect(page.getByLabel('Nome da obra',{exact:true})).toHaveValue('Obra Damata');
 await page.getByRole('button',{name:/02.*Registros fotográficos/}).click();await expect(page.locator('.photo-field img')).toHaveCount(1);
 await page.getByLabel('Pavimento',{exact:true}).press('End');await page.getByLabel('Pavimento',{exact:true}).pressSequentially(' — atualizado');await expect(page.getByLabel('Pavimento',{exact:true})).toHaveValue('3º Subsolo — atualizado');
 await expect(page.getByRole('button',{name:/Exportar PDF/})).toBeEnabled();
 const print=await page.context().newPage();await print.setContent(await frame.locator('html').evaluate(n=>n.outerHTML));await print.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));});
 const pdf=await print.pdf({preferCSSPageSize:true,printBackground:true});await fs.writeFile('test-results/obras.pdf',pdf);
 const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');const doc=await getDocument({data:new Uint8Array(pdf)}).promise;expect(doc.numPages).toBe(await frame.locator('.page').count());const first=await doc.getPage(1);expect(first.view[2]/first.view[3]).toBeCloseTo(16/9,2);
 await print.locator('.fotografico').first().screenshot({path:'test-results/obras-registro.png'});await print.locator('.title-page').screenshot({path:'test-results/obras-contracapa.png'});await print.close();
});
