import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import {novoProjeto,novoItem} from '../src/relatorios/qualidade/modelo';
import {salvarProjeto} from '../src/projeto/arquivo';
test('edição, imagens, projeto portátil, paginação e PDF',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await page.getByRole('button',{name:/MODELO DISPONÍVEL.*Relatório de Qualidade/}).click();
  await page.getByLabel('Cliente',{exact:true}).fill('Cliente do protótipo');
  await page.getByLabel('Projeto / obra').fill('Obra de demonstração');
  await page.getByLabel('Responsável pelo relatório').fill('Equipe de Qualidade');
  await page.getByRole('button',{name:'Continuar para registros'}).click();
  await page.getByRole('button',{name:'Adicionar item'}).click();
  await page.getByLabel('Local',{exact:true}).fill('Pavimento tipo');
  await page.getByLabel('Disciplina',{exact:true}).fill('Rede de dutos');
  await page.getByLabel('Descrição',{exact:true}).fill('Verificar o alinhamento da rede de dutos e registrar as evidências.');
  await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('Recusado');
  await page.locator('.photo-field input').first().setInputFiles('src/identidade/simbolo.png');
  await expect(page.locator('.photo-field img')).toHaveCount(1);
  await expect(page.getByRole('button',{name:'Exportar PDF'})).toBeEnabled();
  const frame=page.frameLocator('iframe');
  await expect(frame.locator('.record')).toHaveCount(1);
  const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:/Salvar projeto/}).click();
  const download=await downloaded;await download.saveAs('test-results/projeto.bcrel');
  // Start afresh, then import the self-contained archive.
  await page.getByRole('button',{name:'Todos os relatórios'}).click();
  await page.locator('input[accept=".bcrel"]').setInputFiles('test-results/projeto.bcrel');
  await expect(page.getByLabel('Cliente',{exact:true})).toHaveValue('Cliente do protótipo');
  await page.getByRole('button',{name:/Registros de inspeção/}).click();
  await expect(page.locator('.photo-field img')).toHaveCount(1);
  await expect(page.getByRole('combobox',{name:'Status',exact:true})).toHaveValue('Recusado');
  // Force continuation pages and prove no description text is dropped.
  const long='Texto de inspeção com descrição longa e detalhes da ocorrência. '.repeat(140)+'FIM DA DESCRIÇÃO';
  await page.getByLabel('Descrição',{exact:true}).fill(long);
  await expect(page.getByRole('button',{name:'Exportar PDF'})).toBeEnabled();
  await expect(frame.locator('.continuation').last()).toContainText('FIM DA DESCRIÇÃO');
  const text=await frame.locator('.description p,.continuation p').allTextContents();
  expect(text.join('')).toBe(long);
  const overflow=await frame.locator('.page main').evaluateAll(nodes=>nodes.some(n=>n.scrollHeight>n.clientHeight+1));expect(overflow).toBe(false);
  const html=await frame.locator('html').evaluate(el=>el.outerHTML);
  const print=await page.context().newPage();await print.setContent(html);await print.evaluate(()=>document.fonts.ready);
  const pdf=await print.pdf({preferCSSPageSize:true,printBackground:true});await fs.writeFile('test-results/prototipo.pdf',pdf);
  const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');const doc=await getDocument({data:new Uint8Array(pdf)}).promise;
  expect(doc.numPages).toBe(await frame.locator('.page').count());
  await print.close();
  await page.getByLabel('Descrição',{exact:true}).fill('Verificar o alinhamento da rede de dutos e registrar as evidências.');
  await expect(page.getByRole('button',{name:'Exportar PDF'})).toBeEnabled();
  await page.screenshot({path:'test-results/prototipo.png',fullPage:true});
  expect(errors).toEqual([]);
});
test('arquivo inválido mantém o trabalho atual',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:/MODELO DISPONÍVEL.*Relatório de Qualidade/}).click();
  await page.getByLabel('Cliente',{exact:true}).fill('Preservar cliente');
  await page.locator('input[accept=".bcrel"]').setInputFiles({name:'invalido.bcrel',mimeType:'application/octet-stream',buffer:Buffer.from('inválido')});
  await page.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();
  await expect(page.getByRole('status')).toBeVisible();
  await expect(page.getByLabel('Cliente',{exact:true})).toHaveValue('Preservar cliente');
});
test('66 registros e observações extensas preservam conteúdo e numeração',async({page})=>{
  const projeto=novoProjeto();projeto.gerais.obra='Teste de volume';
  projeto.itens=Array.from({length:66},(_,n)=>({...novoItem(),descricao:`Ocorrência ${n+1}: verificar suportação e alinhamento.`,local:'Área comum',disciplina:'Rede de dutos'}));
  projeto.observacoes='Observação em uma linha.\n'.repeat(80)+'FIM DAS OBSERVAÇÕES';
  const bytes=await salvarProjeto(projeto);
  await page.goto('/');
  await page.locator('input[accept=".bcrel"]').setInputFiles({name:'volume.bcrel',mimeType:'application/octet-stream',buffer:Buffer.from(bytes)});
  await expect(page.getByRole('button',{name:'Exportar PDF'})).toBeEnabled();
  const frame=page.frameLocator('iframe');
  await expect(frame.locator('.record')).toHaveCount(66);
  const notes=await frame.locator('.observations>p').allTextContents();expect(notes.join('')).toBe(projeto.observacoes);
  const total=await frame.locator('.page').count();
  await expect(frame.locator('.page-number').last()).toHaveText(`Página ${total-1} de ${total}`);
  expect(await frame.locator('.page main').evaluateAll(nodes=>nodes.some(n=>n.scrollHeight>n.clientHeight+1))).toBe(false);
});
