import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import {abrirProjeto} from '../src/projeto/arquivo';
test('colar HTML e TSV, editar, salvar e exportar tabelas extensas',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/MODELO DISPONÍVEL.*Relatório de Avanço/}).click();
 await page.getByRole('button',{name:/03.*Registros descritivos/}).click();await page.getByRole('button',{name:/Adicionar registro descritivo/}).click();
 const field=page.getByLabel('Resumo/Descrição das atividades realizadas',{exact:true});await field.fill('Resumo antes das tabelas.');
 const html='<table><tr><th>Serviço</th><th>Quantidade</th></tr>'+Array.from({length:65},(_,n)=>'<tr><td>Duto '+n+'</td><td>'+n+' metros</td></tr>').join('')+'</table><script>alert(1)</script>';
 await field.evaluate((el,html)=>{const data=new DataTransfer();data.setData('text/html',html);el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));},html);
 await expect(page.getByLabel('Tabela 1, linha 2, coluna 1',{exact:true})).toHaveValue('Duto 0');
 await page.getByLabel('Tabela 1, linha 2, coluna 1',{exact:true}).fill('Duto editado');
 const big='Texto longo na célula. '.repeat(300)+'FIM DA CÉLULA';
 await page.getByLabel('Tabela 1, linha 3, coluna 1',{exact:true}).fill(big);
 await field.evaluate(el=>{const data=new DataTransfer();data.setData('text/plain','Etapa\tStatus\nInstalação\t"Concluída\nConferida"');el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});
 await expect(page.getByLabel('Tabela 2, linha 2, coluna 2',{exact:true})).toHaveValue('Concluída\nConferida');
 await expect(page.getByRole('button',{name:/Exportar PDF/})).toBeEnabled();
 const frame=page.frameLocator('iframe');
 expect((await frame.locator('.activity-table tbody td:first-child').allTextContents()).join('')).toContain(big);
 await expect(frame.locator('.activity-table').first().locator('th')).toHaveText(['Serviço','Quantidade']);
 expect(await frame.locator('.activity-table').count()).toBeGreaterThan(2);
 expect(await frame.locator('.record-page main').evaluateAll(ns=>ns.some(n=>n.scrollHeight>n.clientHeight+1))).toBe(false);
 expect(await frame.locator('script').count()).toBe(0);
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:/Salvar projeto/}).click();await (await downloading).saveAs('test-results/tabelas.bcrel');
 const bytes=await fs.readFile('test-results/tabelas.bcrel');const restored=await abrirProjeto(new Uint8Array(bytes).buffer);if(restored.modelo!=='obras')throw Error('Modelo incorreto');expect(restored.itens[0].tabelas?.[0].linhas[1][0]).toBe('Duto editado');
 await page.getByRole('button',{name:/Todos os relatórios/}).click();await page.locator('input[accept=".bcrel"]').setInputFiles('test-results/tabelas.bcrel');await page.getByRole('button',{name:/03.*Registros descritivos/}).click();
 await expect(page.getByLabel('Tabela 1, linha 2, coluna 1',{exact:true})).toHaveValue('Duto editado');await expect(field).toHaveValue('Resumo antes das tabelas.');
 await expect(page.getByRole('button',{name:/Exportar PDF/})).toBeEnabled();
 const print=await page.context().newPage();await print.setContent(await frame.locator('html').evaluate(n=>n.outerHTML));await print.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));});
 const pdf=await print.pdf({preferCSSPageSize:true,printBackground:true});await fs.writeFile('test-results/tabelas.pdf',pdf);await print.locator('.record-page').filter({has:print.locator('.activity-table')}).first().screenshot({path:'test-results/tabelas.png'});
 const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');const doc=await getDocument({data:new Uint8Array(pdf)}).promise;expect(doc.numPages).toBe(await frame.locator('.page').count());let content='';for(let i=1;i<=doc.numPages;i++)content+=(await (await doc.getPage(i)).getTextContent()).items.map((x:any)=>x.str).join(' ');expect(content).toContain('Duto editado');expect(content).toContain('Duto 64');await print.close();
 await page.getByRole('button',{name:'Remover tabela 2',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await expect(page.locator('.table-editor')).toHaveCount(1);await expect(field).toHaveValue('Resumo antes das tabelas.');
});
