import {useState} from 'react';
import {TabelasDescritivas} from './TabelasDescritivas';
import {Field,Photo} from './Campos';
import {novoRegistro,type ProjetoObras,type RegistroObras} from '../relatorios/obras/modelo';
export function ObrasEditor({project,tab,edit,error,confirmar}:{project:ProjetoObras;tab:string;edit:(p:ProjetoObras)=>void;error:(s:string)=>void;confirmar:(s:string)=>Promise<boolean>}){
 const [selected,setSelected]=useState('');
 const tipo=tab==='itens'?'fotografico':'descritivo';
 const registros=project.itens.filter(i=>i.tipo===tipo);
 const item=registros.find(i=>i.id===selected)||registros[0];
 const update=(patch:Partial<RegistroObras>)=>edit({...project,itens:project.itens.map(i=>i.id===item?.id?{...i,...patch}:i)});
 if(tab==='gerais')return <><div className="hint">A capa utiliza o símbolo da Best Clima. Os campos abaixo aparecem na contracapa.</div><div className="fields"><Field field={{key:'obra',label:'Nome da obra'}} value={project.gerais.obra} change={obra=>edit({...project,gerais:{...project.gerais,obra}})}/><Field field={{key:'tipoRelatorio',label:'Tipo de relatório'}} value={project.gerais.tipoRelatorio} change={tipoRelatorio=>edit({...project,gerais:{...project.gerais,tipoRelatorio}})}/></div></>;
 return <><div className="item-tools"><strong>{registros.length} registro(s)</strong><button className="primary" onClick={()=>{const i=novoRegistro(tipo);edit({...project,itens:[...project.itens,i]});setSelected(i.id);}}>＋ Adicionar registro {tipo==='fotografico'?'fotográfico':'descritivo'}</button></div>{item?<><label className="field"><span>Registro em edição</span><select value={item.id} onChange={e=>setSelected(e.target.value)}>{registros.map((i,n)=><option key={i.id} value={i.id}>{n+1} · {i.servico||'Serviço não informado'}</option>)}</select></label><div className="fields"><Field field={{key:'servico',label:'Serviço realizado'}} value={item.servico} change={servico=>update({servico})}/>{tipo==='fotografico'?<Field field={{key:'pavimento',label:'Pavimento'}} value={item.pavimento} change={pavimento=>update({pavimento})}/>:<Field field={{key:'tipoDescricao',label:'Tipo de descrição'}} value={item.tipoDescricao} change={tipoDescricao=>update({tipoDescricao})}/>}</div>{tipo==='fotografico'&&<><Photo label="Registro fotográfico" value={item.foto} change={foto=>update({foto})} error={error}/><Field field={{key:'legenda',label:'Legenda do registro fotográfico'}} value={item.legenda} change={legenda=>update({legenda})}/></>}{tipo==='descritivo'?<TabelasDescritivas item={item} update={update} error={error} confirmar={confirmar}/>:<Field field={{key:'descricao',label:'Resumo/Descrição das atividades realizadas',type:'textarea'}} value={item.descricao} change={descricao=>update({descricao})}/>}<button className="danger" onClick={async()=>{if(await confirmar('Remover este registro e sua imagem?'))edit({...project,itens:project.itens.filter(i=>i.id!==item.id)});}}>Remover registro</button></>:<div className="empty">Adicione um registro para começar.</div>}</>;
}
